### ISSUE TITLE
NameError: global name 'evaluate' is not defined`

### ISSUE THREAD

**Issue by mon-routeur** [etano/productner#1]
Hello, i have an error when i execute train_classifier.py

`Traceback (most recent call last):
  File "train_classifier.py", line 49, in <module>
    main(sys.argv)
  File "train_classifier.py", line 46, in main
    classifier.train(data, labels)
  File "/root/productner/classifier.py", line 188, in train
    evaluate(x_val, y_val, batch_size)
NameError: global name 'evaluate' is not defined`

Thank you in advance.

**Comment by etano** [comment]
Ok, just pushed a fix. Let me know if that helps!

**Comment by mon-routeur** [comment]
Perfect, train_classify.py work perfectly now, i have an Memory Error when i launch train_ner.py
`Using TensorFlow backend.
Processed 1000000 texts.
Getting labels...
Traceback (most recent call last):
  File "train_ner.py", line 49, in <module>
    main(sys.argv)
  File "train_ner.py", line 42, in main
    labels = ner.get_labels(tags)
  File "/root/productner/ner.py", line 106, in get_labels
    labels = pad_sequences(labels, maxlen=200)
  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/sequence.py", line 57, in pad_sequences
    x = (np.ones((num_samples, maxlen) + sample_shape) * value).astype(dtype)
MemoryError`

Thank you in advance.

**Comment by etano** [comment]
That looks like you're running out of memory. Can you check? Maybe use
fewer than 1000000 texts.

**Comment by mon-routeur** [comment]
Yes, it's a out of memory, when i put 800000 until 1000000, for gettings labels.
But i have an error during the compilation 
`Compiling network...
Traceback (most recent call last):
  File "train_ner.py", line 49, in <module>
    main(sys.argv)
  File "train_ner.py", line 45, in main
    ner.compile(tokenizer)
  File "/root/productner/ner.py", line 157, in compile
    metrics=['acc'])
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 766, in compile
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 952, in compile
    append_metric(i, 'acc', masked_fn(y_true, y_pred, mask=masks[i]))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 484, in masked
    score_array *= mask
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 793, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 575, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype bool for Tensor with dtype float32: 'Tensor("Cast_2:0", shape=(?, 200), dtype=float32)'`

**Comment by mon-routeur** [comment]
Maybe, you prefer that i open an other issue this error ?

**Comment by etano** [comment]
I think it's actually a Tensorflow version error. Can you tell me the
versions of Keras, Python, and Tensorflow that you're using?

Ethan

**Comment by mon-routeur** [comment]
Thank you for your answer.

`python -c "import keras; print keras.__version__"`
`Using TensorFlow backend.
2.0.1`

`python -c "import tensorflow; print tensorflow.__version__"`
`1.0.1`

`python --version`
`Python 2.7.6`

Lionel

**Comment by mon-routeur** [comment]
I do an upgarde of keras and tensorflow, all is ok now !
Thank you so much for your help.

**Comment by mon-routeur** [comment]
I speak too fast :/
An error at the end.
`Traceback (most recent call last):
  File "train_ner.py", line 49, in <module>
    main(sys.argv)
  File "train_ner.py", line 46, in main
    ner.train(data, labels)
  File "/root/productner/ner.py", line 190, in train
    self.evaluate(x_val, y_val, batch_size)
  File "/root/productner/ner.py", line 205, in evaluate
    target_names[self.tag_map[category]] = category
IndexError: list assignment index out of range`

**Comment by etano** [comment]
Confirm that "category" is reasonable. Print out the "tag_map" and
"category" on line 204 probably.

Ethan

**Comment by etano** [comment]
It's been a couple weeks, so I'm going to close this. Open a new issue for other problems. :)

**Comment by kharish99** [comment]
HI I am still getting this same error 
Traceback (most recent call last): File "train_ner.py", line 49, in <module> main(sys.argv) File "train_ner.py", line 46, in main ner.train(data, labels) File "/root/productner/ner.py", line 190, in train self.evaluate(x_val, y_val, batch_size) File "/root/productner/ner.py", line 205, in evaluate target_names[self.tag_map[category]] = category IndexError: list assignment index out of range

there is no different dataset that was used. Still getting this error though.

**Comment by etano** [comment]
I'm going to ask you to debug this please. See the comment above.

**Comment by gauravdevkate** [comment]
from keras import backend as K
import tensorflow as tf
from tensorflow.python.framework.graph_util import convert_variables_to_constants
def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        # Graph -> GraphDef ProtoBuf
        input_graph_def = graph.as_graph_def()
        evaluate()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
    frozen_graph = convert_variables_to_constants(session, input_graph_def,
                                                      output_names, freeze_var_names)
    return frozen_graph
frozen_graph = freeze_session(K.get_session(),
                              output_names=[out.op.name for out in model.outputs])

**Comment by gauravdevkate** [comment]
NameError: name 'evaluate' is not defined
pls anyone help me out
