### ISSUE TITLE
Old issues- Still open - Getting error at the end when the evaluation happens

### ISSUE THREAD

**Issue by kharish99** [etano/productner#8]
Traceback (most recent call last): File "train_ner.py", line 49, in <module> main(sys.argv) File "train_ner.py", line 46, in main ner.train(data, labels) File "/root/productner/ner.py", line 190, in train self.evaluate(x_val, y_val, batch_size) File "/root/productner/ner.py", line 205, in evaluate target_names[self.tag_map[category]] = category IndexError: list assignment index out of range

**Comment by kharish99** [comment]
Hi , Is there any update on the issue above. I am still getting this error at the end.

**Comment by wengquanchi** [comment]
the same question, is there any update on this issue?

**Comment by nuwanarti** [comment]
the same issue occured.. can you please help

**Comment by etano** [comment]
hello everyone. from the looks of it, it would seem that `self.tag_map[category]` is returning a number outside the declared size of `target_names`. I can look into it, but so can you.

**Comment by etano** [comment]
should be fixed now.
